gBerryDescriptionPart1_Cheri:: @ 8589AE4
	.string "매우 귀여운 꽃이 핀다.$"

gBerryDescriptionPart2_Cheri:: @ 8589B09
	.string "새빨간 열매는 아주 맵다.$"

gBerryDescriptionPart1_Chesto:: @ 8589B2D
	.string "겉 부분과 속 모두$"

gBerryDescriptionPart2_Chesto:: @ 8589B52
	.string "딱딱하다. 어느 부분을 먹어도 떫다.$"

gBerryDescriptionPart1_Pecha:: @ 8589B7A
	.string "매우 달고 맛있다.$"

gBerryDescriptionPart2_Pecha:: @ 8589B94
	.string "부드러워서 운반할 때는 주의.$"

gBerryDescriptionPart1_Rawst:: @ 8589BB9
	.string "잎사귀의 부분이 길고 둥글게$"

gBerryDescriptionPart2_Rawst:: @ 8589BDC
	.string "말려 있으면 아주 쓴 듯하다.$"

gBerryDescriptionPart1_Aspear:: @ 8589C01
	.string "딱딱한 열매 속에는 수분이 매우$"

gBerryDescriptionPart2_Aspear:: @ 8589C25
	.string "많이 들어 있다. 꽤 시다.$"

gBerryDescriptionPart1_Leppa:: @ 8589C3E
	.string "버치 등과 비교해 느리게$"

gBerryDescriptionPart2_Leppa:: @ 8589C62
	.string "자란다. 열매가 작은 것일수록 맛있다.$"

gBerryDescriptionPart1_Oran:: @ 8589C86
	.string "여러 가지 맛이 섞인 신기한 열매.$"

gBerryDescriptionPart2_Oran:: @ 8589CAE
	.string "열매를 키우는 데 반나절이 걸린다.$"

gBerryDescriptionPart1_Persim:: @ 8589CCA
	.string "태양을 좋아한다. 햇빛을 받으면$"

gBerryDescriptionPart2_Persim:: @ 8589CEC
	.string "점점 색이 선명해진다.$"

gBerryDescriptionPart1_Lum:: @ 8589D11
	.string "자라는 데 시간이 걸리지만 소중하게$"

gBerryDescriptionPart2_Lum:: @ 8589D35
	.string "키우면 열매가 2개 자라기도 한다.$"

gBerryDescriptionPart1_Sitrus:: @ 8589D54
	.string "오랭과는 형제 같은 존재.$"

gBerryDescriptionPart2_Sitrus:: @ 8589D77
	.string "크고 맛도 고르다.$"

gBerryDescriptionPart1_Figy:: @ 8589D98
	.string "먹힌 듯한 모양 속에는$"

gBerryDescriptionPart2_Figy:: @ 8589DBA
	.string "매운 성분이 가득 차 있다.$"

gBerryDescriptionPart1_Wiki:: @ 8589DD7
	.string "주위에 붙어 있는 돌기는 포켓몬이$"

gBerryDescriptionPart2_Wiki:: @ 8589DFD
	.string "지니기 쉽게 하기 위해서라고 한다.$"

gBerryDescriptionPart1_Mago:: @ 8589E16
	.string "크게 자랄수록 열매가 구부러진다.$"

gBerryDescriptionPart2_Mago:: @ 8589E39
	.string "구부러질수록 달고 맛있다.$"

gBerryDescriptionPart1_Aguav:: @ 8589E5F
	.string "작은 크기의 꽃으로 그것도 빛을$"

gBerryDescriptionPart2_Aguav:: @ 8589E87
	.string "필요로 하지 않는 희귀한 나무열매다.$"

gBerryDescriptionPart1_Iapapa:: @ 8589EA6
	.string "매우 크고 신 나무열매다.$"

gBerryDescriptionPart2_Iapapa:: @ 8589EC6
	.string "키우는 데는 적어도 1일이 걸린다.$"

gBerryDescriptionPart1_Razz:: @ 8589EE7
	.string "빨간 열매는 먹으면 약간 맵고$"

gBerryDescriptionPart2_Razz:: @ 8589F0C
	.string "빠르게 자라서 4시간이면 열매가 열린다.$"

gBerryDescriptionPart1_Bluk:: @ 8589F31
	.string "겉 부분은 파란색이지만 먹으면$"

gBerryDescriptionPart2_Bluk:: @ 8589F57
	.string "입속이 새까맣게 된다.$"

gBerryDescriptionPart1_Nanab:: @ 8589F79
	.string "세상에서 7번째로 발견된 것이$"

gBerryDescriptionPart2_Nanab:: @ 8589F94
	.string "이름의 유래라는 설이 유력하다. 달다.$"

gBerryDescriptionPart1_Wepear:: @ 8589FBA
	.string "The flower is small and white. It has a$"

gBerryDescriptionPart2_Wepear:: @ 8589FE2
	.string "delicate balance of bitter and sour.$"

gBerryDescriptionPart1_Pinap:: @ 858A007
	.string "Weak against wind and cold.$"

gBerryDescriptionPart2_Pinap:: @ 858A023
	.string "The fruit is spicy and the skin, sour.$"

gBerryDescriptionPart1_Pomeg:: @ 858A04A
	.string "However much it is watered,$"

gBerryDescriptionPart2_Pomeg:: @ 858A066
	.string "it only grows up to six BERRIES.$"

gBerryDescriptionPart1_Kelpsy:: @ 858A087
	.string "A rare variety shaped like a root.$"

gBerryDescriptionPart2_Kelpsy:: @ 858A0AA
	.string "Grows a very large flower.$"

gBerryDescriptionPart1_Qualot:: @ 858A0C5
	.string "Loves water. Grows strong even in$"

gBerryDescriptionPart2_Qualot:: @ 858A0E7
	.string "locations with constant rainfall.$"

gBerryDescriptionPart1_Hondew:: @ 858A109
	.string "A BERRY that is very valuable and$"

gBerryDescriptionPart2_Hondew:: @ 858A12B
	.string "rarely seen. It is very delicious.$"

gBerryDescriptionPart1_Grepa:: @ 858A14E
	.string "Despite its tenderness and round$"

gBerryDescriptionPart2_Grepa:: @ 858A16F
	.string "shape, the BERRY is unimaginably sour.$"

gBerryDescriptionPart1_Tamato:: @ 858A196
	.string "The BERRY is lip-bendingly spicy.$"

gBerryDescriptionPart2_Tamato:: @ 858A1B8
	.string "It takes time to grow.$"

gBerryDescriptionPart1_Cornn:: @ 858A1CF
	.string "A BERRY from an ancient era. May not$"

gBerryDescriptionPart2_Cornn:: @ 858A1F4
	.string "grow unless planted in quantity.$"

gBerryDescriptionPart1_Magost:: @ 858A215
	.string "A BERRY that is widely said to have$"

gBerryDescriptionPart2_Magost:: @ 858A239
	.string "a finely balanced flavor.$"

gBerryDescriptionPart1_Rabuta:: @ 858A253
	.string "A rare variety that is overgrown with$"

gBerryDescriptionPart2_Rabuta:: @ 858A279
	.string "hair. It is quite bitter.$"

gBerryDescriptionPart1_Nomel:: @ 858A293
	.string "Quite sour. Just one bite makes it$"

gBerryDescriptionPart2_Nomel:: @ 858A2B6
	.string "impossible to taste for three days.$"

gBerryDescriptionPart1_Spelon:: @ 858A2DA
	.string "The vividly red BERRY is very spicy.$"

gBerryDescriptionPart2_Spelon:: @ 858A2FF
	.string "Its warts secrete a spicy substance.$"

gBerryDescriptionPart1_Pamtre:: @ 858A324
	.string "Drifts on the sea from somewhere.$"

gBerryDescriptionPart2_Pamtre:: @ 858A346
	.string "It is thought to grow elsewhere.$"

gBerryDescriptionPart1_Watmel:: @ 858A367
	.string "A huge BERRY, with some over 20$"

gBerryDescriptionPart2_Watmel:: @ 858A387
	.string "inches discovered. Exceedingly sweet.$"

gBerryDescriptionPart1_Durin:: @ 858A3AD
	.string "Bitter to even look at. It is so$"

gBerryDescriptionPart2_Durin:: @ 858A3CE
	.string "bitter, no one has ever eaten it as is.$"

gBerryDescriptionPart1_Belue:: @ 858A3F6
	.string "It is glossy and looks delicious, but$"

gBerryDescriptionPart2_Belue:: @ 858A41C
	.string "it is awfully sour. Takes time to grow.$"

gBerryDescriptionPart1_Liechi:: @ 858A444
	.string "A mysterious BERRY. It is rumored to$"

gBerryDescriptionPart2_Liechi:: @ 858A469
	.string "contain the power of the sea.$"

gBerryDescriptionPart1_Ganlon:: @ 858A487
	.string "A mysterious BERRY. It is rumored to$"

gBerryDescriptionPart2_Ganlon:: @ 858A4AC
	.string "contain the power of the land.$"

gBerryDescriptionPart1_Salac:: @ 858A4CB
	.string "A mysterious BERRY. It is rumored to$"

gBerryDescriptionPart2_Salac:: @ 858A4F0
	.string "contain the power of the sky.$"

gBerryDescriptionPart1_Petaya:: @ 858A50E
	.string "A mysterious BERRY. It is rumored to$"

gBerryDescriptionPart2_Petaya:: @ 858A533
	.string "contain the power of all living things.$"

gBerryDescriptionPart1_Apicot:: @ 858A55B
	.string "A very mystifying BERRY. No telling$"

gBerryDescriptionPart2_Apicot:: @ 858A57F
	.string "what may happen or how it can be used.$"

gBerryDescriptionPart1_Lansat:: @ 858A5A6
	.string "Said to be a legendary BERRY.$"

gBerryDescriptionPart2_Lansat:: @ 858A5C4
	.string "Holding it supposedly brings joy.$"

gBerryDescriptionPart1_Starf:: @ 858A5E6
	.string "So strong, it was abandoned at the$"

gBerryDescriptionPart2_Starf:: @ 858A609
	.string "world's edge. Considered a mirage.$"

gBerryDescriptionPart1_Enigma:: @ 858A62C
	.string "A completely enigmatic BERRY.$"

gBerryDescriptionPart2_Enigma:: @ 858A64A
	.string "Appears to have the power of stars.$"

